### ISSUE TITLE
combining assets

### ISSUE THREAD

**Issue by Ta2Ta2** [Samuell1/cdn-plugin#2]
Hello, Thanks for the amazing plugin. I'm using below to serve my assets, combining resources.

Only first file is being served. Rest of files are not loaded.

`<script src="{{ cdn('assets/javascript/jquery.js','assets/vendor/bootstrap/js/transition.js','assets/vendor/bootstrap/js/alert.js','assets/vendor/bootstrap/js/button.js','assets/vendor/bootstrap/js/carousel.js','assets/vendor/bootstrap/js/collapse.js','assets/vendor/bootstrap/js/dropdown.js','assets/vendor/bootstrap/js/modal.js','assets/vendor/bootstrap/js/tooltip.js','assets/vendor/bootstrap/js/popover.js','assets/vendor/bootstrap/js/scrollspy.js','assets/vendor/bootstrap/js/tab.js','assets/vendor/bootstrap/js/affix.js','assets/javascript/app.js') }}"></script>`

**Comment by samuelpatro** [comment]
Hey, Thanks!

Sorry but this plugin doesnt support combining assets, you need to do this in your webpack enviroment.
